baseURL: "https://dev--200rx.netlify.app"
languageCode: "en-us"
title: "Ray Miller - IT Infrastructure Specialist [DEV]"
theme: "toha"

# Development-specific parameters
params:
  # Development environment indicators
  environment: "development"
  showEnvironmentBadge: true
  
  # Development API endpoints
  crmApiUrl: "https://200rxio-crm-development.up.railway.app"
  aiApiUrl: "https://portfolio-ai-development.up.railway.app"
  
  # Theme color scheme
  theme:
    backgroundColor: "#06386e"
    secondaryBackgroundColor: "#64ffda1a"
    textColor: "#ffffff"
    secondaryTextColor: "#8892b0"
    neutral: "#ffffff"
    primary: "#64ffda"
    primaryText: "#0a192f"
    secondary: "#172a45"
    secondaryText: "#8892b0"
    accent: "#64ffda"
    accentText: "#0a192f"
    info: "#64ffda"
    infoText: "#0a192f"
    success: "#00d68f"
    successText: "#0a192f"
    warning: "#ffb900"
    warningText: "#0a192f"
    error: "#ff6b6b"
    errorText: "#ffffff"
    
  # Enable features
  enableTocInNavbar: true
  enableBadges: true
  enableTags: true
  enableSearch: true
  enableContactForm: true
  enableRSS: true
  enableBreadcrumb: true
  enableSocialShare: true
  enableComments: false
  
  # Theme features
  features:
    blog:
      enable: true
      title: "Blog"
    notes:
      enable: false
    darkMode:
      enable: true
    theme:
      enable: true
      
  # Custom menu items for additional pages
  customMenus:
    - name: "Services"
      url: "/services"
    - name: "Contact"  
      url: "/contact"
      
  # Custom CSS for layout improvements
  customCss: ["/css/layout-fixes.css"]
  
  # Development analytics (disable or use test IDs)
  analytics:
    google:
      id: "" # Disable in dev or use GA4-DEV-ID
    
  # Development contact form
  contact:
    testMode: true
    
  # Footer
  footer:
    enable: true
    
  # Navbar
  navbar:
    brandName: "Ray Miller"
    showBrandName: true
    showLogo: true
    
# Development build settings
build:
  writeStats: true
  
# Development markup settings  
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    noClasses: false
    
# Enable development features
enableRobotsTXT: false # Disable robots.txt in dev
enableGitInfo: true
enableEmoji: true

# Note: Toha theme uses its own navigation system
# Navigation is controlled by:
# 1. Sections: data/en/sections/*.yaml files (enable: true, showOnNavbar: true)
# 2. Blog: params.features.blog.enable
# 3. Custom menus: params.customMenus

# Pagination
pagination:
  pagerSize: 10
  path: "page"

# Taxonomies
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

# Related content
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: "tags"
      weight: 100
    - name: "categories"
      weight: 200