name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-hugo-resources-${{ hashFiles('config.yaml', 'config.development.yaml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-resources-

      - name: Install theme dependencies
        working-directory: themes/toha
        run: npm ci --legacy-peer-deps

      - name: Install root dependencies
        run: npm ci --legacy-peer-deps

      - name: Build React components
        working-directory: src
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build
        env:
          HUGO_ENVIRONMENT: production
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            hugo --minify --gc --baseURL "${{ steps.pages.outputs.base_url }}/"
          else
            hugo --gc --baseURL "${{ steps.pages.outputs.base_url }}/"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4